sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /swissranger/pointcloud2_raw
    max_range: 2.0
    point_subsample: 1
    shape_padding: 0.01
    shape_scale: 1.0
